# Generated by Django 4.2.6 on 2023-12-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VendorProfileManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                ("contact_details", models.TextField()),
                ("address", models.TextField()),
                ("vendor_code", models.CharField(max_length=125)),
                ("on_time_delivery_rate", models.FloatField(default=None)),
                ("quality_rating_avg", models.FloatField(default=None)),
                ("average_response_time", models.FloatField(default=None)),
                ("fulfillment_rate", models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="po",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=125)),
                ("order_date", models.DateTimeField()),
                ("delivery_date", models.DateTimeField(default=None)),
                ("items", models.JSONField()),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("completed", "completed"),
                            ("canceled", "canceled"),
                        ],
                        max_length=125,
                    ),
                ),
                ("quality_rating", models.FloatField(default=None)),
                ("issue_date", models.DateTimeField(default=None)),
                ("acknowledgment_date", models.DateTimeField(default=None)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intro.vendorprofilemanagement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("on_time_delivery_rate", models.FloatField()),
                ("quality_rating_avg", models.FloatField()),
                ("average_response_time", models.FloatField()),
                ("fulfillment_rate", models.FloatField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intro.vendorprofilemanagement",
                    ),
                ),
            ],
        ),
    ]
