# Generated by Django 4.2.6 on 2023-12-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="po",
            name="acknowledgment_date",
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="po",
            name="issue_date",
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="po",
            name="quality_rating",
            field=models.FloatField(blank=True, default=None),
        ),
    ]
