# Generated by Django 4.2.6 on 2023-12-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intro", "0002_alter_po_acknowledgment_date_alter_po_issue_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="po",
            name="acknowledgment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="po",
            name="issue_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="po",
            name="quality_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
