# Generated by Django 4.2.6 on 2023-12-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intro", "0003_alter_po_acknowledgment_date_alter_po_issue_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="po", name="delivery_date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="po", name="issue_date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="po",
            name="quality_rating",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vendorprofilemanagement",
            name="average_response_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendorprofilemanagement",
            name="fulfillment_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendorprofilemanagement",
            name="on_time_delivery_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendorprofilemanagement",
            name="quality_rating_avg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
